# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
-
  id: "stclient"
  main: ./cmd/client/main.go
  binary: "stclient"
  goos:
    - linux
    - windows
  env:
    - CGO_ENABLED=0
-
  id: "stserver"
  main: ./cmd/server/main.go
  binary: "stserver"
  goos:
    - linux
    - windows
  env:
    - CGO_ENABLED=0
archives:
-
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - stclient.json
    - stserver.json
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
